---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: Azure NetApp Files permet aux entreprises de migrer et d’exécuter leurs applications stratégiques gourmandes en performances et sensibles à la latence dans Azure sans avoir besoin de refactoriser pour le cloud. 
---
= En savoir plus sur Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files permet aux entreprises de migrer et d’exécuter leurs applications stratégiques gourmandes en performances et sensibles à la latence dans Azure sans avoir besoin de refactoriser pour le cloud.



== Caractéristiques

* La prise en charge de plusieurs protocoles permet aux applications Linux et Windows de s'exécuter de manière transparente dans Azure.
* Plusieurs niveaux de performances permettent un alignement étroit avec les exigences de performances de la charge de travail.
* Les principales certifications, notamment SAP HANA, GDPR et HIPAA, permettent la migration des charges de travail les plus exigeantes vers Azure.




=== Fonctionnalités supplémentaires dans la NetApp Console

* Migrez les données NFS ou SMB vers Azure NetApp Files directement depuis la NetApp Console.  Les migrations de données sont optimisées par NetApp Copy and Sync.
+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["En savoir plus sur la copie et la synchronisation"^]

* Grâce à la technologie basée sur l’intelligence artificielle (IA), NetApp Data Classification peut vous aider à comprendre le contexte des données et à identifier les données sensibles qui résident dans vos comptes Azure NetApp Files .
+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["En savoir plus sur la classification des données"^]





== NetApp Console

Azure NetApp Files est accessible via la NetApp Console.

La NetApp Console fournit une gestion centralisée des services de stockage et de données NetApp dans les environnements sur site et cloud à l'échelle de l'entreprise. La console est requise pour accéder aux services de données NetApp et les utiliser. En tant qu'interface de gestion, il vous permet de gérer de nombreuses ressources de stockage à partir d'une seule interface. Les administrateurs de console peuvent contrôler l’accès au stockage et aux services pour tous les systèmes de l’entreprise.

Vous n'avez pas besoin de licence ni d'abonnement pour commencer à utiliser NetApp Console et vous n'encourez des frais que lorsque vous devez déployer des agents de console dans votre cloud pour garantir la connectivité à vos systèmes de stockage ou à vos services de données NetApp . Cependant, certains services de données NetApp accessibles depuis la console sont sous licence ou basés sur un abonnement.

En savoir plus sur lelink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"^] .



== Coût

https://azure.microsoft.com/pricing/details/netapp/["Afficher les tarifs Azure NetApp Files"^]

L’abonnement et la facturation sont gérés par le service Azure NetApp Files , et non par la console.



== Régions prises en charge

https://bluexp.netapp.com/cloud-volumes-global-regions["Afficher les régions Azure prises en charge"^]



== Obtenir de l'aide

Pour les problèmes de support technique associés à Azure NetApp Files, utilisez le portail Azure pour enregistrer une demande de support auprès de Microsoft.  Sélectionnez votre abonnement Microsoft associé et sélectionnez le nom du service * Azure NetApp Files* sous *Stockage*.  Fournissez les informations restantes requises pour créer votre demande d’assistance Microsoft.



== Liens connexes

* link:https://bluexp.netapp.com/azure-netapp-files["Site Web de la NetApp Console : Azure NetApp Files"^]
* link:https://learn.microsoft.com/azure/azure-netapp-files/["Documentation Azure NetApp Files"^]
* link:https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["Copier et synchroniser la documentation"^]

