---
settings:
  name: Azure NetApp Files
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Azure NetApp Files
    url: "/index.html"
  - title: Notes de version
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencer
    entries:
    - title: En savoir plus sur Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Démarrage du flux de travail
      url: "/task-quick-start.html"
    - title: Configurer une application Microsoft Entra
      url: "/task-set-up-azure-ad.html"
    - title: Créer un système
      url: "/task-create-system.html"
  - title: Utiliser Azure NetApp Files
    entries:
    - title: Créer et monter des volumes
      url: "/task-create-volumes.html"
    - title: Gérer les volumes existants
      url: "/task-manage-volumes.html"
    - title: Supprimer les Azure NetApp Files
      url: "/task-remove-system.html"
  - title: Connaissances et soutien
    entries:
    - title: Inscrivez-vous pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenir de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
